### ISSUE TITLE
auto-build cri image can't run 

### ISSUE THREAD

**Issue by jsparter** [sealerio/basefs#42]
#### What happened:
I build a cri image with auto-build : `./auto-build.sh --k8s-version=v1.24.0 -c=containerd --push false`
Then I run with Clusterfile:
```
apiVersion: sealer.io/v2
kind: Cluster
metadata:
  creationTimestamp: null
  name: my-cluster
spec:
  containerRuntime:
    type: containerd
  env:
  - LocalRegistryDomain=sea.hub
  - LocalRegistryPort=5000
  - LocalRegistryURL=sea.hub:5000
  - RegistryDomain=sea.hub
  - RegistryPort=5000
  - RegistryURL=sea.hub:5000
  - ContainerRuntime=containerd
  hosts:
  - ips:
    - xxxx
    roles:
    - master
    ssh: {}
  image: localhost/containerdcluster:v1
  registry:
    localRegistry:
      cert: {}
      domain: sea.hub
      ha: true
      insecure: false
      port: 5000
  ssh:
    passwd: xxxx
    pk: /root/.ssh/id_rsa
    port: "22"
    user: root
status: {}
```
it report an error:
```
[ERROR] [root.go:75] sealer-unknown: failed to install containerd: execute command(ContainerRuntime="containerd" LocalRegistryDomain="sea.hub" LocalRegistryPort="5000" LocalRegistryURL="sea.hub:5000" RegistryDomain="sea.hub" RegistryPort="5000" RegistryURL="sea.hub:5000" && bash /var/lib/sealer/data/my-cluster/rootfs/scripts/containerd.sh) on host (172.16.158.197): error(failed to execute command(ContainerRuntime="containerd" LocalRegistryDomain="sea.hub" LocalRegistryPort="5000" LocalRegistryURL="sea.hub:5000" RegistryDomain="sea.hub" RegistryPort="5000" RegistryURL="sea.hub:5000" && bash /var/lib/sealer/data/my-cluster/rootfs/scripts/containerd.sh) on host(172.16.158.197): error(exit status 2))
```
when I run containerd.sh, it report:
```
+ tar zxvf '../cri/cri-*.tar.gz' -C /
tar (child): ../cri/cri-*.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

#### What you expected to happen:
run successfully
#### Environment:

- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
