### ISSUE TITLE
install_libseccomp.sh 执行问题

### ISSUE THREAD

**Issue by fangzhengjin** [sealerio/basefs#54]
请问 install_libseccomp.sh 会在何时被执行呢? 我看了下sealer的源码, 没有看到有执行此脚本的任务

**Comment by kakaZhou719** [comment]
@fangzhengjin ,使用的是那个镜像呢？

**Comment by fangzhengjin** [comment]
@kakaZhou719 是自定义镜像, 我希望从`scratch `开始创建一个镜像, 使用当前仓库的基础脚本, 我提到的脚本位于当前仓库的`basefs/context/rootfs/lib/install_libseccomp.sh`

另外提一句, 官网的文档实在是太旧了, 和新版的差异有些大, 我看到在使用Shell Plugin时, 文档中的action是PreInit, 新版代码里的好像是PreInitHost

**Comment by kakaZhou719** [comment]
> @kakaZhou719 是自定义镜像, 我希望从`scratch `开始创建一个镜像, 使用当前仓库的基础脚本, 我提到的脚本位于当前仓库的`basefs/context/rootfs/lib/install_libseccomp.sh`
> 
> 另外提一句, 官网的文档实在是太旧了, 和新版的差异有些大, 我看到在使用Shell Plugin时, 文档中的action是PreInit, 新版代码里的好像是PreInitHost, 初次接触的时候会让人很困惑, 找不到Shell插件为何没有执行

 `basefs/context/rootfs/lib/install_libseccomp.sh` 这个脚本是在安装 container runtime中使用的
 官网文档，可以看最新的：http://sealer.cool/docs/concept/clusterfile.html#plugin-api

**Comment by fangzhengjin** [comment]
我构建的镜像是基于container runtime的, 但是直到container启动时, 都没有调用这个脚本安装libseccomp

关于文档的问题, 是因为我点了切换中文, 所以被定向到了8.x版本的文档, 或许我们可以在旧版文档页面顶部添加一个明显的提醒来告诉大家此文档不是最新的? 只有英文版才有最新的

**Comment by fangzhengjin** [comment]
我添加了一个shell插件来手动执行`install_libseccomp.sh`

plugin/shell.yaml
```yaml
apiVersion: sealer.aliyun.com/v1alpha1
kind: Plugin
metadata:
  name: install-libseccomp
spec:
  type: SHELL
  action: PreInit
  data: |
    lib/install_libseccomp.sh
```


```
FROM scratch
...............
COPY plugin plugin
CNI calico local://calico.sh
LAUNCH ["calico"]
```

但是没有奏效, `containerd.sh`执行前并没有运行此插件, 是哪里出了问题吗?
